### ISSUE TITLE
flashcap: configure purging of guest simulations on alpha/beta

### ISSUE THREAD

**Issue by robnagler** [radiasoft/devops#200]

**Comment by robnagler** [comment]
I configured alpha and beta as follows:

```yml
        job_supervisor:
          max_hours:
            parallel: .1
          purge_non_premium_after_days: 1
          purge_non_premium_task_secs: 1:0:0
```

Simulations will only stick around a day for non-premium users, and you'll only get 6 minutes of runtime on parallel. We can extend this once we see that it works.
