### ISSUE TITLE
travis-ci.org shutting down

### ISSUE THREAD

**Issue by robnagler** [radiasoft/devops#219]
> Please be aware travis-ci.org will be shutting down in several weeks, with all accounts migrating to travis-ci.com. Please stay tuned here for more information.

We use Travis a bit, but it's quite decoupled. It might just work, but we'll see...

**Comment by robnagler** [comment]
Consider using GitHub CI

**Comment by robnagler** [comment]
Played with GitHub Actions, and they are a bit strange, considering they are tied to a repo. You have to initiate a checkout. The file is [.github/workflows/go.yml](https://github.com/robnagler/ci-play/blob/03b843059628b340426ff5dd8238ffb5dc22dcc7/.github/workflows/go.yml):

```yml
name: go
on:
  push:
    branches:
      - master
jobs:
  job1:
    name: job1
    runs-on: ubuntu-latest
    steps:
      - id: step1
        uses: actions/checkout@v2
      - id: step2
        run: bash github.sh
```

I don't think it's going to work for sirepo or pykern, because [any user with write access to your repository has read access to all secrets configured in your repository](https://docs.github.com/en/actions/learn-github-actions/security-hardening-for-github-actions#using-secrets).

I thought about configuring another repo that has the secrets, but there's no cross repo triggers that don't require secrets to the other repo.

Too bad.
