### ISSUE TITLE
Increase disk size

### ISSUE THREAD

**Issue by e-carlin** [radiasoft/devops#263]
@jeinstei has requested a disk size of 500GB+

Here is what we have currently on the machine
```bash
~# pvs
  PV         VG     Fmt  Attr PSize    PFree
  /dev/sda2  centos lvm2 a--  <475.94g <321.94g
  /dev/sdb1  centos lvm2 a--  <476.94g <476.94g
~# lvs
  LV   VG     Attr       LSize   Pool Origin Data%  Meta%  Move Log Cpy%Sync Convert
  root centos -wi-ao----  50.00g
  srv  centos -wi-ao---- 100.00g
  swap centos -wi-ao----   4.00g
```

This is my first time increasing the size of available disk so @robnagler please confirm this looks right:
```bash
lvextend -L+400.0G /dev/centos/srv
resize2fs /dev/centos/srv
```

**Comment by robnagler** [comment]
rsconf does everything:

```yml
        volume_groups:
          centos:
            logical_volumes:
              {{ _volume_srv(100) }}
```

Just change 100 to 500, run.sh, then run rsc on the machine.
